#!/usr/bin/env bash
# Configures a Nginx server to listen to port 80
# Remove the default Nginx configuration file 
rm /etc/nginx/sites-enabled/default

# Configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
