#!/usr/bin/env bash
# prints the content of the file /etc/passwd
# only prints the username, user id and home directory path for the user

while read -r line
do
	echo "$line" | cut -d: -f1,4,7
done < "/etc/passwd"
