#!/usr/bin/env bash
# uses while loop from 1 to 10 and:
# displays "bad luck" at no. 4 and "good luck" at no. 8
# displays "Best School" for the other numbers

i=1
while ((i <= 10))
do
    if ((i != 4 && i != 8))
    then
        echo 'Best School'
    elif ((i == 4))
    then
        echo 'bad luck'
    else
        echo 'good luck'
    fi
	((i++))
done
