#!/usr/bin/env bash
# uses while loop and case statement to print numbers 1 to 20 and:
# prints 4 and then "bad luck from China"
# prints 9 and then "bad luck from Japan"
# prints 17 and then "bad luck from Italy"

i=1
while ((i <= 20))
do
    echo $i
    case $i in
		4)
			echo 'bad luck from China'
			;;
		9)
			echo 'bad luck from Japan'
			;;
		17)
			echo 'bad luck from Italy'
			;;
    esac
    ((i++))
done
